#!/bin/sh
set -e
		
pl="/var/cache/etckeeper/packagelist"
NL="
"

if etckeeper unclean; then
	message="committing changes in /etc after $HIGHLEVEL_PACKAGE_MANAGER run"
	separator="$NL${NL}Package changes:$NL"
	maxdifflen=$(expr 131071 - ${#message} - ${#separator})
	if [ -e $pl.pre-install ]; then
		diff="$(etckeeper list-installed | diff -U0 $pl.pre-install - | tail -n+4 | egrep '^[-+]' | head -c $maxdifflen)" || true
		if [ -n "$diff" ]; then
			message="$message$separator$diff"
		fi
		rm -f $pl.pre-install
	fi

	etckeeper commit "$(printf "$message")"
fi
